#!/bin/bash
rm /home/terce/.android/avd/Pixel_3a_API_33_x86_64.avd/multiinstance.lock
rm /home/terce/.android/avd/Pixel_3a_API_33_x86_64.avd/hardware-qemu.ini.lock
echo "fichiers lock de l'emulateur android éffacés !"
